server.port=8080

firebase.project-id=${FIREBASE_PROJECT_ID:}
firebase.use-emulator=${USE_FIREBASE_EMULATOR:false}
firebase.emulator-host=${FIRESTORE_EMULATOR_HOST:}

gemini.api-key=${GEMINI_API_KEY:}
gemini.model=${GEMINI_MODEL:gemini-3.5-flash}
